# Generated by Django 4.1.4 on 2022-12-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='dislikes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meme',
            name='likes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
