# Generated by Django 4.1.4 on 2023-01-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_meme_dislikes_meme_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meme',
            options={'ordering': ['confidence']},
        ),
        migrations.AddField(
            model_name='meme',
            name='confidence',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
