# Generated by Django 4.1.4 on 2023-01-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_meme_options_meme_confidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meme',
            options={'ordering': ['-confidence']},
        ),
        migrations.AlterField(
            model_name='meme',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
    ]
